version: "3.4"

services:
    makentu:
        container_name: makentu
        env_file:
            - .env
        build:
            context: .
            dockerfile: ./Dockerfile
        ports:
            - "8000:8000"
        environment:
            MONGO_URL: mongodb://mongodb
        expose:
            - "8000"
        volumes:
            - .:/app/
        restart: always

    mongodb:
        image: mongo
        container_name: mongodb
        restart: always
        ports:
            - "27017:27017"
